[general]
OPENAI_API_KEY="sk-...only needed in case you use table summarize..."

[default]
# api_key="zwt_cg7zotvbMIUFl87cbAnBnc8wDgaPv_eXT5nkkA"
api_key = "zwt_bz6DahCpCW3mNHwmXpYDU2pwhfaHgYFB_tlPLg"
