vectara:
  corpus_id: 25
  customer_id: 1169579801
  reindex: true

crawling:
  crawler_type: folder

folder_crawler:
  path: "/Users/ofer/Downloads/transformer-papers/"
  extensions: ['.pdf']
  source: 'pdf-folder'

