vectara:
  corpus_id: 2
  customer_id: 1913582498
  reindex: false

crawling:
  crawler_type: rss

rss_crawler:
  source: gpss
  rss_pages: [
    # "https://gpss2.tipo.gov.tw/gpsskmc/gpssbkm?@@664453987", "https://gpss2.tipo.gov.tw/gpssbkmusr/00021/TWAA-202413948.pdf"
    "http://feeds.bbci.co.uk/news/rss.xml", "http://feeds.bbci.co.uk/news/world/rss.xml", "http://feeds.bbci.co.uk/news/uk/rss.xml",
    "http://feeds.bbci.co.uk/news/business/rss.xml", "http://feeds.bbci.co.uk/news/politics/rss.xml", 
    "http://feeds.bbci.co.uk/news/health/rss.xml", "http://feeds.bbci.co.uk/news/education/rss.xml", 
    "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml", "http://feeds.bbci.co.uk/news/technology/rss.xml", 
    "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml", "http://feeds.bbci.co.uk/news/world/middle_east/rss.xml",
    "http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml", "http://feeds.bbci.co.uk/news/world/asia/rss.xml",
    "http://feeds.bbci.co.uk/news/world/europe/rss.xml"
  ]
  days_past: 365
  delay: 1
  extraction: playwright           # pdf or playwright
